settings:
  database:
    host:
      10.240.37.20
    port:
      3306
    user:
      jumpserver
    password:
      jumpserver
    dbname:
      hiveview

  application:
    host:
      0.0.0.0
    port:
      9090

  ansible:
    factsdir:
      /tmp/fact
    inventory:
      /root/getAnsibleHost.py
  log:
    logpath:
      D:\goproject\src\hiveview\log\
    logname:
      hiveview.log
    accesslogpath:
      D:\goproject\src\hiveview\log\
    accesslogname:
      hiveview_access.log
